AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'new Sam app

  example passs

  '
Resources:
  PassThroughFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://passthroughproject/9f73327271ff3d9f09b01e9a1102a4f2
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        HelloWorldAPI:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
